services:
  - type: web
    name: personascape-api
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /api/test-cors
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false 